/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CreategameRouteImport } from './routes/creategame'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoingameSessionIdRouteImport } from './routes/joingame/$sessionId'

const CreategameRoute = CreategameRouteImport.update({
  id: '/creategame',
  path: '/creategame',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoingameSessionIdRoute = JoingameSessionIdRouteImport.update({
  id: '/joingame/$sessionId',
  path: '/joingame/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/creategame': typeof CreategameRoute
  '/joingame/$sessionId': typeof JoingameSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/creategame': typeof CreategameRoute
  '/joingame/$sessionId': typeof JoingameSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/creategame': typeof CreategameRoute
  '/joingame/$sessionId': typeof JoingameSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/creategame' | '/joingame/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/creategame' | '/joingame/$sessionId'
  id: '__root__' | '/' | '/about' | '/creategame' | '/joingame/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CreategameRoute: typeof CreategameRoute
  JoingameSessionIdRoute: typeof JoingameSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/creategame': {
      id: '/creategame'
      path: '/creategame'
      fullPath: '/creategame'
      preLoaderRoute: typeof CreategameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joingame/$sessionId': {
      id: '/joingame/$sessionId'
      path: '/joingame/$sessionId'
      fullPath: '/joingame/$sessionId'
      preLoaderRoute: typeof JoingameSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CreategameRoute: CreategameRoute,
  JoingameSessionIdRoute: JoingameSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
